"""
This script serves as the core unification component for structural
predictions generated by multiple complex prediction methods. It loads structure
files from different modeling pipelines, extracts standardized metadata from each
individual model, and organizes the predictions into a unified dataset that can be
used for downstream comparative analyses.

The design separates two conceptual layers (this document doing part 2):

1. Single-Structure Extraction
   These operations process one structure file at a time and extract standardized
   metadata describing that prediction.
   - Method parsing: Determine which prediction method produced the structure
     based on directory structure or file paths.
   - Structure loading: Parse .pdb or .cif files using the appropriate Biopython
     parser.
   - Chain identification: Identify the target chain based on its known fixed
     sequence length and determine the corresponding binder chain(s).
   - Sequence extraction: Extract the binder amino acid sequence from the
     structure to provide a consistent identifier across prediction methods.
   - Optional structure features: Extract additional per-structure information
     (e.g., residue contacts or structural metadata) for later analysis.

2. Dataset-Level Unification
   After metadata has been extracted from all individual structures, the dataset
   is aggregated to enable cross-method comparison and filtering.
   - Binder grouping: Group predictions originating from different methods by
     their binder sequence, allowing consistent identification of equivalent
     complexes.
   - Master dataset compilation: Construct a unified dataset (e.g., dataframe or
     record list) containing standardized metadata for all predictions.
   - Smart filtering (future extension): Select representative predictions per
     binder (e.g., highest-ranking prediction) while preserving access to all raw
     predictions.
   - Comparative analysis (future extension): Enable reliable cross-method
     structural comparisons such as binder-binder RMSD and target-target RMSD.

Overall flow:
    -> method parsing
    -> structure loading
    -> chain identification
    -> binder sequence extraction
    -> binder sequence matching
    -> unified dataset compilation
"""

from itertools import combinations, permutations
import pandas as pd
import numpy as np
from pathlib import Path
from joblib import Parallel, delayed
import tempfile
import os
import gemmi
from tqdm.auto import tqdm

from Bio.PDB import PDBParser, MMCIFParser, Superimposer, NeighborSearch
from Bio.PDB.Polypeptide import is_aa

def build_rank1_method_pairs(
        df: pd.DataFrame,
        binder_col: str = "binder_sequence",
        method_col: str = "method",
        structure_file_col: str = "path",
        rank_col: str = "rank",
        file_type_col: str = "file_type",
        binder_id_col: str = "binder_chain_id",
        target_id_col: str = "target_chain_id",
        keep_cols: list[str] | None = None,
        directed: bool = False,
    ) -> pd.DataFrame:
    if keep_cols is None:
        keep_cols = ["score", "score_name"]

    required = [binder_col, method_col, structure_file_col, rank_col, file_type_col, binder_id_col, target_id_col]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    
    cols_to_use = required + [c for c in keep_cols if c in df.columns]
    work = df[cols_to_use].copy()

    work = work[work[rank_col] == 1].copy()

    work = work.dropna(subset=[binder_col, method_col, structure_file_col, file_type_col, binder_id_col, target_id_col])

    dup_mask = work.duplicated(subset=[binder_col, method_col], keep=False)
    if dup_mask.any():
        dup_df = work.loc[dup_mask, [binder_col, method_col, structure_file_col, file_type_col, binder_id_col, target_id_col]]
        raise ValueError("Found multiple rank-1 rows for the same binder_sequence and method.\n"
                         f"Examples:\n{dup_df.head(10)}")
    
    pair_rows = []

    for binder_seq, group in work.groupby(binder_col, sort=False):
        if len(group) < 2:
            continue

        records = group.to_dict("records")

        pair_iter = permutations(records, 2) if directed else combinations(records, 2)

        for rec1, rec2 in pair_iter:
            row = {
                binder_col: binder_seq,

                ("reference_method" if directed else "method_1"): rec1[method_col],
                ("query_method" if directed else "method_2"): rec2[method_col],

                "structure_path_1": rec1[structure_file_col],
                "structure_path_2": rec2[structure_file_col],
                "file_type_1": rec1[file_type_col],
                "file_type_2": rec2[file_type_col],
                "binder_chain_1": rec1[binder_id_col],
                "binder_chain_2": rec2[binder_id_col],
                "target_chain_1": rec1[target_id_col],
                "target_chain_2": rec2[target_id_col],
            }

            for c in keep_cols:
                if c in rec1:
                    row[f"{c}_1"] = rec1[c]
                if c in rec2:
                    row[f"{c}_2"] = rec2[c]
            
            pair_rows.append(row)

    pair_df = pd.DataFrame(pair_rows)

    if not pair_df.empty:
        sort_cols = ([binder_col, "reference_method", "query_method"] if directed else [binder_col, "method_1", "method_2"])

        pair_df = pair_df.sort_values(by=sort_cols).reset_index(drop=True)

    return pair_df

### RMSD Calculation Binder-on-binder

def cif_to_tmp_pdb(cif_path):
    cif_path = Path(cif_path)

    doc = gemmi.cif.read_file(str(cif_path))
    structure = gemmi.make_structure_from_block(doc.sole_block())

    tmp = tempfile.NamedTemporaryFile(suffix=".pdb", delete=False)
    structure.write_pdb(tmp.name)
    tmp.close()
    return tmp.name

def load_structure_biopython(path, file_type=None, structure_id=None):
    path = Path(path)

    if structure_id is None:
        structure_id = path.stem

    if file_type is None:
        suffix = path.suffix.lower()
        if suffix == ".pdb":
            file_type = "pdb"
        elif suffix == ".cif":
            file_type == "cif"
        else:
            raise ValueError(f"Could not infer file type from suffix: {path}")
        
    file_type = str(file_type).lower().strip().lstrip(".")

    if file_type == "pdb":
        parser = PDBParser(QUIET=True)
        return parser.get_structure(structure_id, str(path))

    elif file_type in {"cif", "mmcif"}:
        try:
            parser = MMCIFParser(QUIET=True)
            return parser.get_structure(structure_id, str(path))
        except Exception:
            tmp_pdb = cif_to_tmp_pdb(path)
            try:
                parser = PDBParser(QUIET=True)
                return parser.get_structure(structure_id, tmp_pdb)
            finally:
                if os.path.exists(tmp_pdb):
                    os.unlink(tmp_pdb)

    else:
        raise ValueError(f"Unsupported file type: {file_type}")

def get_chain_by_id(structure, chain_id):
    for model in structure:
        for chain in model:
            if chain.id == chain_id:
                return chain
    
    available = []
    for model in structure:
        available.extend([chain.id for chain in model])

    raise KeyError(f"Chain '{chain_id}' not found. Available chains: {sorted(set(available))}")

def extract_protein_ca_atoms(chain):
    ca_atoms = []

    for residue in chain:
        if residue.id[0] != " ":
            continue

        if not is_aa(residue, standard=False):
            continue

        if "CA" in residue:
            ca_atoms.append(residue["CA"])

    return ca_atoms

def compute_binder_ca_rmsd_aligned_on_binder(path_1, path_2, binder_chain_1, binder_chain_2, file_type_1=None, file_type_2=None):
    try:
        structure_1 = load_structure_biopython(path_1, file_type=file_type_1, structure_id="ref")
        structure_2 = load_structure_biopython(path_2, file_type=file_type_2, structure_id="mov")

        chain_1 = get_chain_by_id(structure_1, binder_chain_1)
        chain_2 = get_chain_by_id(structure_2, binder_chain_2)

        ca_atoms_1 = extract_protein_ca_atoms(chain_1)
        ca_atoms_2 = extract_protein_ca_atoms(chain_2)

        len_1 = len(ca_atoms_1)
        len_2 = len(ca_atoms_2)

        if len_1 == 0 or len_2 == 0:
            return {
                "binder_ca_rmsd_align_binder": np.nan,
                "n_ca_aligned": 0,
                "binder_len_1": len_1,
                "binder_len_2": len_2,
                "status": "failed",
                "error": "One or both binder chains have no CA atoms."                
            }
        
        if len_1 != len_2:
            return {
                "binder_ca_rmsd_align_binder": np.nan,
                "n_ca_aligned": min(len_1, len_2),
                "binder_len_1": len_1,
                "binder_len_2": len_2,
                "status": "failed",
                "error": (
                    f"Binder CA atom counts differ: {len_1} vs {len_2}. "
                    "Cannot safely superimpose by one-to-one residue order."
                )                
            }
        
        sup = Superimposer()
        sup.set_atoms(ca_atoms_1, ca_atoms_2)

        return {
            "binder_ca_rmsd_align_binder": float(sup.rms),
            "n_ca_aligned": len_1,
            "binder_len_1": len_1,
            "binder_len_2": len_2,
            "status": "ok",
            "error": None         
        }
    
    except Exception as e:
        return {
            "binder_ca_rmsd_align_binder": np.nan,
            "n_ca_aligned": 0,
            "binder_len_1": np.nan,
            "binder_len_2": np.nan,
            "status": "failed",
            "error": str(e)            
        }

def compute_binder_ca_rmsd_for_row(row):
    return compute_binder_ca_rmsd_aligned_on_binder(
        path_1=row["structure_path_1"],
        path_2=row["structure_path_2"],
        binder_chain_1=row["binder_chain_1"],
        binder_chain_2=row["binder_chain_2"],
        file_type_1=row.get("file_type_1"),
        file_type_2=row.get("file_type_2"),
    )

### All atom binder RMSD

def extract_protein_common_atoms(chain_1, chain_2):
    atoms_1 = []
    atoms_2 = []

    residues_1 = [
        r for r in chain_1
        if r.id[0] == " " and is_aa(r, standard=False)
    ]

    residues_2 = [
        r for r in chain_2
        if r.id[0] == " " and is_aa(r, standard=False)
    ]

    if len(residues_1) != len(residues_2):
        return atoms_1, atoms_2, len(residues_1), len(residues_2)

    for res1, res2 in zip(residues_1, residues_2):
        atom_names_1 = {atom.name for atom in res1}
        atom_names_2 = {atom.name for atom in res2}

        common_atom_names = sorted(atom_names_1 & atom_names_2)

        # Optional: skip hydrogens if present
        common_atom_names = [
            name for name in common_atom_names
            if not name.startswith("H")
        ]

        for atom_name in common_atom_names:
            atoms_1.append(res1[atom_name])
            atoms_2.append(res2[atom_name])

    return atoms_1, atoms_2, len(residues_1), len(residues_2)

def compute_binder_all_atom_rmsd_aligned_on_binder(
    path_1,
    path_2,
    binder_chain_1,
    binder_chain_2,
    file_type_1=None,
    file_type_2=None):

    try:
        structure_1 = load_structure_biopython(
            path_1, file_type=file_type_1, structure_id="ref"
        )
        structure_2 = load_structure_biopython(
            path_2, file_type=file_type_2, structure_id="mov"
        )

        chain_1 = get_chain_by_id(structure_1, binder_chain_1)
        chain_2 = get_chain_by_id(structure_2, binder_chain_2)

        atoms_1, atoms_2, binder_len_1, binder_len_2 = extract_protein_common_atoms(
            chain_1,
            chain_2
        )

        n_atoms = len(atoms_1)

        if binder_len_1 != binder_len_2:
            return {
                "binder_all_atom_rmsd_align_binder": np.nan,
                "n_atoms_aligned": n_atoms,
                "binder_len_1": binder_len_1,
                "binder_len_2": binder_len_2,
                "status_all_atom": "failed",
                "error_all_atom": (
                    f"Binder residue counts differ: {binder_len_1} vs {binder_len_2}. "
                    "Cannot safely superimpose by residue order."
                )
            }

        if n_atoms == 0:
            return {
                "binder_all_atom_rmsd_align_binder": np.nan,
                "n_atoms_aligned": 0,
                "binder_len_1": binder_len_1,
                "binder_len_2": binder_len_2,
                "status_all_atom": "failed",
                "error_all_atom": "No common atoms found between binder chains."
            }

        sup = Superimposer()
        sup.set_atoms(atoms_1, atoms_2)

        return {
            "binder_all_atom_rmsd_align_binder": float(sup.rms),
            "n_atoms_aligned": n_atoms,
            "binder_len_1": binder_len_1,
            "binder_len_2": binder_len_2,
            "status_all_atom": "ok",
            "error_all_atom": None
        }

    except Exception as e:
        return {
            "binder_all_atom_rmsd_align_binder": np.nan,
            "n_atoms_aligned": 0,
            "binder_len_1": np.nan,
            "binder_len_2": np.nan,
            "status_all_atom": "failed",
            "error_all_atom": str(e)
        }

def compute_binder_all_atom_rmsd_for_row(row):
    return compute_binder_all_atom_rmsd_aligned_on_binder(
        path_1=row["structure_path_1"],
        path_2=row["structure_path_2"],
        binder_chain_1=row["binder_chain_1"],
        binder_chain_2=row["binder_chain_2"],
        file_type_1=row.get("file_type_1", None),
        file_type_2=row.get("file_type_2", None),
    )

### Binder RMSD when aligned on target within 10 Å of binder (pocket specific alignment)
### Do method pairs agree on the local binding pose/orientation relative to the target pocket?

def get_protein_residues(chain):
    residues = []
    for residue in chain:
        if residue.id[0] != " ":
            continue
        if not is_aa(residue, standard=False):
            continue
        residues.append(residue)
    return residues

def residue_key(residue, mode="id"):
    """
    Key used to match target residues between structures.

    ``mode="id"`` matches by residue number and insertion code.
    ``mode="position"`` matches by zero-based protein-residue position.
    """
    if mode == "id":
        return (int(residue.id[1]), residue.id[2].strip())
    raise ValueError(f"Unsupported residue key mode: {mode}")

def get_residue_dict_by_key(chain, mode="id"):
    residues = get_protein_residues(chain)
    if mode == "position":
        return {i: res for i, res in enumerate(residues)}
    return {residue_key(res, mode=mode): res for res in residues}

def get_target_interface_residue_keys(
    target_chain,
    binder_chain,
    cutoff=5.0,
    residue_match_mode="id",
):
    """
    Return target residue keys whose atoms are within ``cutoff`` Angstrom of
    any binder atom.
    """
    target_residues = get_protein_residues(target_chain)
    binder_atoms = [
        atom
        for residue in get_protein_residues(binder_chain)
        for atom in residue.get_atoms()
    ]

    if not binder_atoms:
        return []

    ns = NeighborSearch(binder_atoms)
    interface_keys = []

    for position, residue in enumerate(target_residues):
        key = position if residue_match_mode == "position" else residue_key(
            residue, mode=residue_match_mode
        )
        for atom in residue.get_atoms():
            if ns.search(atom.coord, cutoff):
                interface_keys.append(key)
                break

    return interface_keys

def get_target_shell_residues(target_chain, binder_chain, cutoff=5.0):
    target_residues = get_protein_residues(target_chain)
    binder_atoms = [
        atom
        for residue in get_protein_residues(binder_chain)
        for atom in residue.get_atoms()
    ]

    if not binder_atoms:
        return []

    ns = NeighborSearch(binder_atoms)
    shell_residues = []

    for residue in target_residues:
        for atom in residue.get_atoms():
            if ns.search(atom.coord, cutoff):
                shell_residues.append(residue)
                break
    # this is the list of resiudes in the interface of the target
    return shell_residues

def get_residue_position_dict(chain):
    residues = get_protein_residues(chain)
    return {res: i for i, res in enumerate(residues)}


def get_residue_dict_by_position(chain):
    residues = get_protein_residues(chain)
    return {i: res for i, res in enumerate(residues)}

def get_matched_ca_atoms_from_residue_keys(
    chain_1,
    chain_2,
    residue_keys,
    residue_match_mode="id",
):
    res_dict_1 = get_residue_dict_by_key(chain_1, mode=residue_match_mode)
    res_dict_2 = get_residue_dict_by_key(chain_2, mode=residue_match_mode)

    atoms_1 = []
    atoms_2 = []

    for key in residue_keys:
        res1 = res_dict_1.get(key)
        res2 = res_dict_2.get(key)

        if res1 is None or res2 is None:
            continue
        if "CA" not in res1 or "CA" not in res2:
            continue

        atoms_1.append(res1["CA"])
        atoms_2.append(res2["CA"])

    return atoms_1, atoms_2

def get_matched_ca_atoms_from_residue_positions(chain_1, chain_2, positions):
    return get_matched_ca_atoms_from_residue_keys(
        chain_1,
        chain_2,
        positions,
        residue_match_mode="position",
    )

def calc_interface_overlap(interface_keys_1, interface_keys_2):
    keys_1 = set(interface_keys_1)
    keys_2 = set(interface_keys_2)
    shared_keys = sorted(keys_1 & keys_2)

    if not keys_1 or not keys_2:
        return {
            "shared_keys": shared_keys,
            "overlap_method_1": 0.0,
            "overlap_method_2": 0.0,
            "overlap_max": 0.0,
        }

    overlap_1 = len(shared_keys) / len(keys_1)
    overlap_2 = len(shared_keys) / len(keys_2)
    return {
        "shared_keys": shared_keys,
        "overlap_method_1": float(overlap_1),
        "overlap_method_2": float(overlap_2),
        "overlap_max": float(max(overlap_1, overlap_2)),
    }

def calc_rmsd_from_atoms(atom_list_1, atom_list_2, rot, tran):
    # Apply the rotation/translation that maps structure 2 onto structure 1,
    # then compute RMSD against structure 1 coordinates.

    coords_1 = np.array([atom.coord for atom in atom_list_1], dtype=float)
    coords_2 = np.array([atom.coord for atom in atom_list_2], dtype=float)

    coords_2_transformed = np.dot(coords_2, rot) + tran

    diff = coords_1 - coords_2_transformed
    rmsd = np.sqrt(np.mean(np.sum(diff * diff, axis=1)))
    return float(rmsd)

def _failed_result(
    error,
    cutoff,
    n_interface_residues_1=np.nan,
    n_interface_residues_2=np.nan,
    n_shared_interface_residues=0,
    interface_overlap_method_1=np.nan,
    interface_overlap_method_2=np.nan,
    interface_overlap_max=np.nan,
    alignment_mode=None,
    n_alignment_residues_selected=0,
    n_alignment_ca_aligned=0,
    n_binder_ca_compared=0,
):
    return {
        "binder_ca_rmsd_pocket_align": np.nan,
        "n_shell_residues_ref": n_interface_residues_1,
        "n_shell_ca_aligned": n_alignment_ca_aligned,
        "n_binder_ca_compared": n_binder_ca_compared,
        "target_shell_cutoff": cutoff,
        "status_target_shell": "failed",
        "error_target_shell": error,
        "n_interface_residues_1": n_interface_residues_1,
        "n_interface_residues_2": n_interface_residues_2,
        "n_shared_interface_residues": n_shared_interface_residues,
        "interface_overlap_method_1": interface_overlap_method_1,
        "interface_overlap_method_2": interface_overlap_method_2,
        "interface_overlap_max": interface_overlap_max,
        "alignment_mode": alignment_mode,
        "n_alignment_residues_selected": n_alignment_residues_selected,
        "n_alignment_ca_aligned": n_alignment_ca_aligned,
    }

def compute_binder_ca_rmsd_aligned_on_target_shell(
    path_1,
    path_2,
    binder_chain_1,
    binder_chain_2,
    target_chain_1,
    target_chain_2,
    file_type_1=None,
    file_type_2=None,
    cutoff=5.0,
    overlap_threshold=0.50,
    residue_match_mode="id",
):
    try:
        structure_1 = load_structure_biopython(path_1, file_type=file_type_1, structure_id="ref")
        structure_2 = load_structure_biopython(path_2, file_type=file_type_2, structure_id="mov")

        binder_1 = get_chain_by_id(structure_1, binder_chain_1)
        binder_2 = get_chain_by_id(structure_2, binder_chain_2)
        target_1 = get_chain_by_id(structure_1, target_chain_1)
        target_2 = get_chain_by_id(structure_2, target_chain_2)

        interface_keys_1 = get_target_interface_residue_keys(
            target_chain=target_1,
            binder_chain=binder_1,
            cutoff=cutoff,
            residue_match_mode=residue_match_mode,
        )
        interface_keys_2 = get_target_interface_residue_keys(
            target_chain=target_2,
            binder_chain=binder_2,
            cutoff=cutoff,
            residue_match_mode=residue_match_mode,
        )

        n_interface_1 = len(interface_keys_1)
        n_interface_2 = len(interface_keys_2)


        if n_interface_1 == 0:
            return _failed_result(
                "No target-interface residues found in reference structure.",
                cutoff=cutoff,
                n_interface_residues_1=n_interface_1,
                n_interface_residues_2=n_interface_2,
                interface_overlap_method_1=0.0,
                interface_overlap_method_2=0.0,
                interface_overlap_max=0.0,
            )

        overlap = calc_interface_overlap(interface_keys_1, interface_keys_2)
        shared_keys = overlap["shared_keys"]
        overlap_max = overlap["overlap_max"]

        if overlap_max >= overlap_threshold:
            alignment_keys = shared_keys
            alignment_mode = "shared_interface"
        else:
            alignment_keys = interface_keys_1
            alignment_mode = "reference_interface"

        if len(alignment_keys) == 0:
            return _failed_result(
                "No target-interface residues selected for alignment.",
                cutoff=cutoff,
                n_interface_residues_1=n_interface_1,
                n_interface_residues_2=n_interface_2,
                n_shared_interface_residues=len(shared_keys),
                interface_overlap_method_1=overlap["overlap_method_1"],
                interface_overlap_method_2=overlap["overlap_method_2"],
                interface_overlap_max=overlap_max,
                alignment_mode=alignment_mode,
            )

        shell_ca_1, shell_ca_2 = get_matched_ca_atoms_from_residue_keys(
            target_1,
            target_2,
            alignment_keys,
            residue_match_mode=residue_match_mode,
        )

        if len(shell_ca_1) < 3:
            return _failed_result(
                f"Too few matched target-interface CA atoms for superposition: {len(shell_ca_1)}",
                cutoff=cutoff,
                n_interface_residues_1=n_interface_1,
                n_interface_residues_2=n_interface_2,
                n_shared_interface_residues=len(shared_keys),
                interface_overlap_method_1=overlap["overlap_method_1"],
                interface_overlap_method_2=overlap["overlap_method_2"],
                interface_overlap_max=overlap_max,
                alignment_mode=alignment_mode,
                n_alignment_residues_selected=len(alignment_keys),
                n_alignment_ca_aligned=len(shell_ca_1),
            )

        sup = Superimposer()
        sup.set_atoms(shell_ca_1, shell_ca_2)
        rot, tran = sup.rotran

        binder_ca_1 = extract_protein_ca_atoms(binder_1)
        binder_ca_2 = extract_protein_ca_atoms(binder_2)

        if len(binder_ca_1) == 0 or len(binder_ca_2) == 0:
            return _failed_result(
                "One or both binder chains have no CA atoms.",
                cutoff=cutoff,
                n_interface_residues_1=n_interface_1,
                n_interface_residues_2=n_interface_2,
                n_shared_interface_residues=len(shared_keys),
                interface_overlap_method_1=overlap["overlap_method_1"],
                interface_overlap_method_2=overlap["overlap_method_2"],
                interface_overlap_max=overlap_max,
                alignment_mode=alignment_mode,
                n_alignment_residues_selected=len(alignment_keys),
                n_alignment_ca_aligned=len(shell_ca_1),
            )

        if len(binder_ca_1) != len(binder_ca_2):
            return _failed_result(
                f"Binder CA atom counts differ: {len(binder_ca_1)} vs {len(binder_ca_2)}",
                cutoff=cutoff,
                n_interface_residues_1=n_interface_1,
                n_interface_residues_2=n_interface_2,
                n_shared_interface_residues=len(shared_keys),
                interface_overlap_method_1=overlap["overlap_method_1"],
                interface_overlap_method_2=overlap["overlap_method_2"],
                interface_overlap_max=overlap_max,
                alignment_mode=alignment_mode,
                n_alignment_residues_selected=len(alignment_keys),
                n_alignment_ca_aligned=len(shell_ca_1),
                n_binder_ca_compared=min(len(binder_ca_1), len(binder_ca_2)),
            )

        binder_rmsd = calc_rmsd_from_atoms(
            atom_list_1=binder_ca_1,
            atom_list_2=binder_ca_2,
            rot=rot,
            tran=tran,
        )

        return {
            "binder_ca_rmsd_pocket_align": binder_rmsd,
            "n_shell_residues_ref": n_interface_1,
            "n_shell_ca_aligned": len(shell_ca_1),
            "n_binder_ca_compared": len(binder_ca_1),
            "target_shell_cutoff": cutoff,
            "status_target_shell": "ok",
            "error_target_shell": None,
            "n_interface_residues_1": n_interface_1,
            "n_interface_residues_2": n_interface_2,
            "n_shared_interface_residues": len(shared_keys),
            "interface_overlap_method_1": overlap["overlap_method_1"],
            "interface_overlap_method_2": overlap["overlap_method_2"],
            "interface_overlap_max": overlap_max,
            "interface_overlap_threshold": overlap_threshold,
            "alignment_mode": alignment_mode,
            "n_alignment_residues_selected": len(alignment_keys),
            "n_alignment_ca_aligned": len(shell_ca_1),
            "residue_match_mode": residue_match_mode,
        }

    except Exception as e:
        return _failed_result(str(e), cutoff=cutoff)

def compute_target_shell_rmsd_for_row(
    row,
    cutoff=5.0,
    overlap_threshold=0.50,
    residue_match_mode="id",
):
    return compute_binder_ca_rmsd_aligned_on_target_shell(
        path_1=row["structure_path_1"],
        path_2=row["structure_path_2"],
        binder_chain_1=row["binder_chain_1"],
        binder_chain_2=row["binder_chain_2"],
        target_chain_1=row["target_chain_1"],
        target_chain_2=row["target_chain_2"],
        file_type_1=row["file_type_1"],
        file_type_2=row["file_type_2"],
        cutoff=cutoff,
        overlap_threshold=overlap_threshold,
        residue_match_mode=residue_match_mode,
    )


if __name__ == "__main__":
    PAIR_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/rmsd_data/new_parquets/5Å/pairwise_method_comparisons_rank1_only_5Å.parquet")

    RMSD_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/rmsd_data/new_parquets/5Å/pairwise_method_comparisons_rank1_with_binder_aligned_rmsd_5Å.parquet")

    ALL_ATOM_RMSD_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/rmsd_data/new_parquets/5Å/pairwise_method_comparisons_rank1_with_binder_all_atom_rmsd_5Å.parquet")

    SHELL_PAIR_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/rmsd_data/new_parquets/5Å/directed_method_comparisons_rank1_only_5Å.parquet")

    SHELL_RMSD_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/rmsd_data/new_parquets/5Å/directed_method_comparisons_rank1_with_overlap_target_pocket_rmsd_5Å.parquet")

    df = pd.read_parquet("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/prediction_records_new.parquet")

    # BASE TRIANGULAR PAIRS FOR SYMMETRIC BINDER RMSD ALIGNED ON BINDER

    pair_df = build_rank1_method_pairs(
        df,
        binder_col="binder_sequence",
        method_col="method",
        structure_file_col="path",
        rank_col="rank",
        file_type_col="file_type",
        binder_id_col="binder_chain_id",
        target_id_col="target_chain_id",
        keep_cols=["score", "score_name"],
        directed=False,
    )

    # Save the base pair dataframe
    pair_df.to_parquet(PAIR_PATH, index=False)

    print(pair_df.groupby("binder_sequence").size().value_counts())
    print(pair_df.head())
    print(f"Number of triangular pairwise comparisons: {len(pair_df)}")
    print(f"Saved to: {PAIR_PATH}")

    # Compute binder CA RMSD aligned on binder - Triangular

    results = Parallel(n_jobs=-2, verbose=10)(
        delayed(compute_binder_ca_rmsd_for_row)(row)
        for _, row in pair_df.iterrows()
    )

    results_df = pd.DataFrame(results)

    pair_df_with_rmsd = pd.concat(
        [pair_df.reset_index(drop=True), results_df],
        axis=1
    )

    print(pair_df_with_rmsd[
        [
            "method_1",
            "method_2",
            "binder_ca_rmsd_align_binder",
            "n_ca_aligned",
            "status",
            "error",
        ]
    ].head())

    print(pair_df_with_rmsd["status"].value_counts(dropna=False))

    pair_df_with_rmsd.to_parquet(RMSD_PATH, index=False)
    print(f"Saved binder CA RMSD results to: {RMSD_PATH}")

    # Binder aligned all-atom RMSD - Triangular

    all_atom_results = Parallel(n_jobs=-2, verbose=10)(
    delayed(compute_binder_all_atom_rmsd_for_row)(row)
    for _, row in pair_df.iterrows())

    all_atom_results_df = pd.DataFrame(all_atom_results)

    pair_df_with_all_atom_rmsd = pd.concat(
    [pair_df.reset_index(drop=True), all_atom_results_df],
    axis=1)

    print(pair_df_with_all_atom_rmsd[
    [
        "method_1",
        "method_2",
        "binder_all_atom_rmsd_align_binder",
        "n_atoms_aligned",
        "status_all_atom",
        "error_all_atom",
    ]].head())

    print(pair_df_with_all_atom_rmsd["status_all_atom"].value_counts(dropna=False))

    pair_df_with_all_atom_rmsd.to_parquet(ALL_ATOM_RMSD_PATH, index=False)

    print(f"Saved all-atom RMSD results to: {ALL_ATOM_RMSD_PATH}")
 
    # --------------------------------------------------
    # 4. Directed pairs for target-shell RMSD
    # --------------------------------------------------

    shell_pair_df = build_rank1_method_pairs(
        df,
        binder_col="binder_sequence",
        method_col="method",
        structure_file_col="path",
        rank_col="rank",
        file_type_col="file_type",
        binder_id_col="binder_chain_id",
        target_id_col="target_chain_id",
        keep_cols=["score", "score_name"],
        directed=True,
    )

    shell_pair_df.to_parquet(SHELL_PAIR_PATH, index=False)

    print(shell_pair_df.groupby("binder_sequence").size().value_counts())
    print(shell_pair_df.head())
    print(f"Number of directed target-shell comparisons: {len(shell_pair_df)}")
    print(f"Saved directed pairs to: {SHELL_PAIR_PATH}")

    # --------------------------------------------------
    # 5. Target-shell RMSD — directed
    # --------------------------------------------------

    shell_results = Parallel(n_jobs=-2, verbose=10)(
        delayed(compute_target_shell_rmsd_for_row)(row, 5.0)
        for _, row in shell_pair_df.iterrows()
    )

    shell_results_df = pd.DataFrame(shell_results)

    pair_df_with_shell_rmsd = pd.concat(
        [shell_pair_df.reset_index(drop=True), shell_results_df],
        axis=1
    )

    print(pair_df_with_shell_rmsd[
        [
            "reference_method",
            "query_method",
            "binder_ca_rmsd_pocket_align",
            "n_interface_residues_1",
            "n_interface_residues_2",
            "n_shared_interface_residues",
            "interface_overlap_method_1",
            "interface_overlap_method_2",
            "interface_overlap_max",
            "alignment_mode",
            "n_alignment_ca_aligned",
            "n_binder_ca_compared",
            "status_target_shell",
            "error_target_shell",
        ]].head())


    print(pair_df_with_shell_rmsd["status_target_shell"].value_counts(dropna=False))
    print(pair_df_with_shell_rmsd["alignment_mode"].value_counts(dropna=False))
    print(pair_df_with_shell_rmsd["interface_overlap_max"].describe())


    pair_df_with_shell_rmsd.to_parquet(SHELL_RMSD_PATH, index=False)
    print(f"Saved directed target-shell RMSD results to: {SHELL_RMSD_PATH}")