"""
This script serves as the core unification component for structural
predictions generated by multiple complex prediction methods. It loads structure
files from different modeling pipelines, extracts standardized metadata from each
individual model, and organizes the predictions into a unified dataset that can be
used for downstream comparative analyses.

The design separates two conceptual layers (this document doing part 2):

1. Single-Structure Extraction
   These operations process one structure file at a time and extract standardized
   metadata describing that prediction.
   - Method parsing: Determine which prediction method produced the structure
     based on directory structure or file paths.
   - Structure loading: Parse .pdb or .cif files using the appropriate Biopython
     parser.
   - Chain identification: Identify the target chain based on its known fixed
     sequence length and determine the corresponding binder chain(s).
   - Sequence extraction: Extract the binder amino acid sequence from the
     structure to provide a consistent identifier across prediction methods.
   - Optional structure features: Extract additional per-structure information
     (e.g., residue contacts or structural metadata) for later analysis.

2. Dataset-Level Unification
   After metadata has been extracted from all individual structures, the dataset
   is aggregated to enable cross-method comparison and filtering.
   - Binder grouping: Group predictions originating from different methods by
     their binder sequence, allowing consistent identification of equivalent
     complexes.
   - Master dataset compilation: Construct a unified dataset (e.g., dataframe or
     record list) containing standardized metadata for all predictions.
   - Smart filtering (future extension): Select representative predictions per
     binder (e.g., highest-ranking prediction) while preserving access to all raw
     predictions.
   - Comparative analysis (future extension): Enable reliable cross-method
     structural comparisons such as binder-binder RMSD and target-target RMSD.

Overall flow:
    -> method parsing
    -> structure loading
    -> chain identification
    -> binder sequence extraction
    -> binder sequence matching
    -> unified dataset compilation
"""

from itertools import combinations
import pandas as pd
import numpy as np
from pathlib import Path
from joblib import Parallel, delayed
import tempfile
import os
import gemmi

from Bio.PDB import PDBParser, MMCIFParser, Superimposer, NeighborSearch
from Bio.PDB.Polypeptide import is_aa

def build_rank1_method_pairs(
        df: pd.DataFrame,
        binder_col: str = "binder_sequence",
        method_col: str = "method",
        structure_file_col: str = "path",
        rank_col: str = "rank",
        file_type_col: str = "file_type",
        binder_id_col: str = "binder_chain_id",
        target_id_col: str = "target_chain_id",
        keep_cols: list[str] | None = None,
    ) -> pd.DataFrame:
    if keep_cols is None:
        keep_cols = ["score", "score_name"]

    required = [binder_col, method_col, structure_file_col, rank_col, file_type_col, binder_id_col, target_id_col]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    
    cols_to_use = required + [c for c in keep_cols if c in df.columns]
    work = df[cols_to_use].copy()

    work = work[work[rank_col] == 1].copy()

    work = work.dropna(subset=[binder_col, method_col, structure_file_col, file_type_col, binder_id_col, target_id_col])

    dup_mask = work.duplicated(subset=[binder_col, method_col], keep=False)
    if dup_mask.any():
        dup_df = work.loc[dup_mask, [binder_col, method_col, structure_file_col, file_type_col, binder_id_col, target_id_col]]
        raise ValueError("Found multiple rank-1 rows for the same binder_sequence and method.\n"
                         f"Examples:\n{dup_df.head(10)}")
    
    pair_rows = []

    for binder_seq, group in work.groupby(binder_col, sort=False):
        if len(group) < 2:
            continue

        records = group.to_dict("records")

        for rec1, rec2 in combinations(records, 2):
            row = {
                binder_col: binder_seq,
                "method_1": rec1[method_col],
                "method_2": rec2[method_col],
                "structure_path_1": rec1[structure_file_col],
                "structure_path_2": rec2[structure_file_col],
                "file_type_1": rec1[file_type_col],
                "file_type_2": rec2[file_type_col],
                "binder_chain_1": rec1[binder_id_col],
                "binder_chain_2": rec2[binder_id_col],
                "target_chain_1": rec1[target_id_col],
                "target_chain_2": rec2[target_id_col],
            }

            for c in keep_cols:
                if c in rec1:
                    row[f"{c}_1"] = rec1[c]
                if c in rec2:
                    row[f"{c}_2"] = rec2[c]
            
            pair_rows.append(row)

    pair_df = pd.DataFrame(pair_rows)

    if not pair_df.empty:
        pair_df = pair_df.sort_values(
            by=[binder_col, "method_1", "method_2"]
        ).reset_index(drop=True)

    return pair_df

### RMSD Calculation Binder-on-binder

def cif_to_tmp_pdb(cif_path):
    cif_path = Path(cif_path)

    doc = gemmi.cif.read_file(str(cif_path))
    structure = gemmi.make_structure_from_block(doc.sole_block())

    tmp = tempfile.NamedTemporaryFile(suffix=".pdb", delete=False)
    structure.write_pdb(tmp.name)
    tmp.close()
    return tmp.name

def load_structure_biopython(path, file_type=None, structure_id=None):
    path = Path(path)

    if structure_id is None:
        structure_id = path.stem

    if file_type is None:
        suffix = path.suffix.lower()
        if suffix == ".pdb":
            file_type = "pdb"
        elif suffix == ".cif":
            file_type == "cif"
        else:
            raise ValueError(f"Could not infer file type from suffix: {path}")
        
    file_type = str(file_type).lower().strip().lstrip(".")

    if file_type == "pdb":
        parser = PDBParser(QUIET=True)
        return parser.get_structure(structure_id, str(path))

    elif file_type in {"cif", "mmcif"}:
        try:
            parser = MMCIFParser(QUIET=True)
            return parser.get_structure(structure_id, str(path))
        except Exception:
            tmp_pdb = cif_to_tmp_pdb(path)
            try:
                parser = PDBParser(QUIET=True)
                return parser.get_structure(structure_id, tmp_pdb)
            finally:
                if os.path.exists(tmp_pdb):
                    os.unlink(tmp_pdb)

    else:
        raise ValueError(f"Unsupported file type: {file_type}")

def get_chain_by_id(structure, chain_id):
    for model in structure:
        for chain in model:
            if chain.id == chain_id:
                return chain
    
    available = []
    for model in structure:
        available.extend([chain.id for chain in model])

    raise KeyError(f"Chain '{chain_id}' not found. Available chains: {sorted(set(available))}")

def extract_protein_ca_atoms(chain):
    ca_atoms = []

    for residue in chain:
        if residue.id[0] != " ":
            continue

        if not is_aa(residue, standard=False):
            continue

        if "CA" in residue:
            ca_atoms.append(residue["CA"])

    return ca_atoms

def compute_binder_ca_rmsd_aligned_on_binder(path_1, path_2, binder_chain_1, binder_chain_2, file_type_1=None, file_type_2=None):
    try:
        structure_1 = load_structure_biopython(path_1, file_type=file_type_1, structure_id="ref")
        structure_2 = load_structure_biopython(path_2, file_type=file_type_2, structure_id="mov")

        chain_1 = get_chain_by_id(structure_1, binder_chain_1)
        chain_2 = get_chain_by_id(structure_2, binder_chain_2)

        ca_atoms_1 = extract_protein_ca_atoms(chain_1)
        ca_atoms_2 = extract_protein_ca_atoms(chain_2)

        len_1 = len(ca_atoms_1)
        len_2 = len(ca_atoms_2)

        if len_1 == 0 or len_2 == 0:
            return {
                "binder_ca_rmsd_align_binder": np.nan,
                "n_ca_aligned": 0,
                "binder_len_1": len_1,
                "binder_len_2": len_2,
                "status": "failed",
                "error": "One or both binder chains have no CA atoms."                
            }
        
        if len_1 != len_2:
            return {
                "binder_ca_rmsd_align_binder": np.nan,
                "n_ca_aligned": min(len_1, len_2),
                "binder_len_1": len_1,
                "binder_len_2": len_2,
                "status": "failed",
                "error": (
                    f"Binder CA atom counts differ: {len_1} vs {len_2}. "
                    "Cannot safely superimpose by one-to-one residue order."
                )                
            }
        
        sup = Superimposer()
        sup.set_atoms(ca_atoms_1, ca_atoms_2)

        return {
            "binder_ca_rmsd_align_binder": float(sup.rms),
            "n_ca_aligned": len_1,
            "binder_len_1": len_1,
            "binder_len_2": len_2,
            "status": "ok",
            "error": None         
        }
    
    except Exception as e:
        return {
            "binder_ca_rmsd_align_binder": np.nan,
            "n_ca_aligned": 0,
            "binder_len_1": np.nan,
            "binder_len_2": np.nan,
            "status": "failed",
            "error": str(e)            
        }

def compute_binder_ca_rmsd_for_row(row):
    return compute_binder_ca_rmsd_aligned_on_binder(
        path_1=row["structure_path_1"],
        path_2=row["structure_path_2"],
        binder_chain_1=row["binder_chain_1"],
        binder_chain_2=row["binder_chain_2"],
        file_type_1=row.get("file_type_1"),
        file_type_2=row.get("file_type_2"),
    )

### Binder RMSD when aligned on target within 10 Å of binder (pocket specific alignment)
### Do method pairs agree on the local binding pose/orientation relative to the target pocket?

def get_protein_residues(chain):
    residues = []
    for residue in chain:
        if residue.id[0] != " ":
            continue
        if not is_aa(residue, standard=False):
            continue
        residues.append(residue)
    return residues

def get_target_shell_residues(target_chain, binder_chain, cutoff=10.0):
    target_residues = get_protein_residues(target_chain)
    binder_atoms = [
        atom
        for residue in get_protein_residues(binder_chain)
        for atom in residue.get_atoms()
    ]

    if not binder_atoms:
        return []

    ns = NeighborSearch(binder_atoms)
    shell_residues = []

    for residue in target_residues:
        for atom in residue.get_atoms():
            if ns.search(atom.coord, cutoff):
                shell_residues.append(residue)
                break
    # this is the list of resiudes in the interface of the target
    return shell_residues

def residue_key(residue):
    hetflag, resseq, icode = residue.id
    return (resseq, icode)

def get_residue_dict(chain):
    return {residue_key(res): res for res in get_protein_residues(chain)}

def get_matched_ca_atoms_from_residue_keys(chain_1, chain_2, keys):
    # for two targets
    res_dict_1 = get_residue_dict(chain_1)
    res_dict_2 = get_residue_dict(chain_2)

    atoms_1 = []
    atoms_2 = []

    for key in keys:
        res1 = res_dict_1.get(key)
        res2 = res_dict_2.get(key)

        if res1 is None or res2 is None:
            continue
        if "CA" not in res1 or "CA" not in res2:
            continue

        atoms_1.append(res1["CA"])
        atoms_2.append(res2["CA"])

    return atoms_1, atoms_2

def calc_rmsd_from_atoms(atom_list_1, atom_list_2, rot, tran):
    # Apply the rotation/translation that maps structure 2 onto structure 1,
    # then compute RMSD against structure 1 coordinates.

    coords_1 = np.array([atom.coord for atom in atom_list_1], dtype=float)
    coords_2 = np.array([atom.coord for atom in atom_list_2], dtype=float)

    coords_2_transformed = np.dot(coords_2, rot) + tran

    diff = coords_1 - coords_2_transformed
    rmsd = np.sqrt(np.mean(np.sum(diff * diff, axis=1)))
    return float(rmsd)

def compute_binder_ca_rmsd_aligned_on_target_shell(
    path_1,
    path_2,
    binder_chain_1,
    binder_chain_2,
    target_chain_1,
    target_chain_2,
    file_type_1=None,
    file_type_2=None,
    cutoff=10.0,
):
    try:
        structure_1 = load_structure_biopython(path_1, file_type=file_type_1, structure_id="ref")
        structure_2 = load_structure_biopython(path_2, file_type=file_type_2, structure_id="mov")

        binder_1 = get_chain_by_id(structure_1, binder_chain_1)
        binder_2 = get_chain_by_id(structure_2, binder_chain_2)
        target_1 = get_chain_by_id(structure_1, target_chain_1)
        target_2 = get_chain_by_id(structure_2, target_chain_2)

        # --- shell residues from reference structure target
        shell_residues_1 = get_target_shell_residues(
            target_chain=target_1,
            binder_chain=binder_1,
            cutoff=cutoff,
        )

        shell_keys = [residue_key(res) for res in shell_residues_1]

        if len(shell_keys) == 0:
            return {
                "binder_ca_rmsd_align_target_shell": np.nan,
                "n_shell_residues_ref": 0,
                "n_shell_ca_aligned": 0,
                "n_binder_ca_compared": 0,
                "target_shell_cutoff": cutoff,
                "status_target_shell": "failed",
                "error_target_shell": "No target-shell residues found in reference structure.",
            }

        shell_ca_1, shell_ca_2 = get_matched_ca_atoms_from_residue_keys(
            target_1, target_2, shell_keys
        )

        if len(shell_ca_1) < 3:
            return {
                "binder_ca_rmsd_align_target_shell": np.nan,
                "n_shell_residues_ref": len(shell_keys),
                "n_shell_ca_aligned": len(shell_ca_1),
                "n_binder_ca_compared": 0,
                "target_shell_cutoff": cutoff,
                "status_target_shell": "failed",
                "error_target_shell": (
                    f"Too few matched target-shell CA atoms for superposition: {len(shell_ca_1)}"
                ),
            }

        # --- superimpose on target shell
        sup = Superimposer()
        sup.set_atoms(shell_ca_1, shell_ca_2)
        rot, tran = sup.rotran

        # --- binder CA atoms for RMSD
        binder_ca_1 = extract_protein_ca_atoms(binder_1)
        binder_ca_2 = extract_protein_ca_atoms(binder_2)

        if len(binder_ca_1) == 0 or len(binder_ca_2) == 0:
            return {
                "binder_ca_rmsd_align_target_shell": np.nan,
                "n_shell_residues_ref": len(shell_keys),
                "n_shell_ca_aligned": len(shell_ca_1),
                "n_binder_ca_compared": 0,
                "target_shell_cutoff": cutoff,
                "status_target_shell": "failed",
                "error_target_shell": "One or both binder chains have no CA atoms.",
            }

        if len(binder_ca_1) != len(binder_ca_2):
            return {
                "binder_ca_rmsd_align_target_shell": np.nan,
                "n_shell_residues_ref": len(shell_keys),
                "n_shell_ca_aligned": len(shell_ca_1),
                "n_binder_ca_compared": min(len(binder_ca_1), len(binder_ca_2)),
                "target_shell_cutoff": cutoff,
                "status_target_shell": "failed",
                "error_target_shell": (
                    f"Binder CA atom counts differ: {len(binder_ca_1)} vs {len(binder_ca_2)}"
                ),
            }

        binder_rmsd = calc_rmsd_from_atoms(
            atom_list_1=binder_ca_1,
            atom_list_2=binder_ca_2,
            rot=rot,
            tran=tran,
        )

        return {
            "binder_ca_rmsd_align_target_shell": binder_rmsd,
            "n_shell_residues_ref": len(shell_keys),
            "n_shell_ca_aligned": len(shell_ca_1),
            "n_binder_ca_compared": len(binder_ca_1),
            "target_shell_cutoff": cutoff,
            "status_target_shell": "ok",
            "error_target_shell": None,
        }

    except Exception as e:
        return {
            "binder_ca_rmsd_align_target_shell": np.nan,
            "n_shell_residues_ref": np.nan,
            "n_shell_ca_aligned": 0,
            "n_binder_ca_compared": 0,
            "target_shell_cutoff": cutoff,
            "status_target_shell": "failed",
            "error_target_shell": str(e),
        }

def compute_target_shell_rmsd_for_row(row, cutoff=10.0):
    return compute_binder_ca_rmsd_aligned_on_target_shell(
        path_1=row["structure_path_1"],
        path_2=row["structure_path_2"],
        binder_chain_1=row["binder_chain_1"],
        binder_chain_2=row["binder_chain_2"],
        target_chain_1=row["target_chain_1"],
        target_chain_2=row["target_chain_2"],
        file_type_1=row["file_type_1"],
        file_type_2=row["file_type_2"],
        cutoff=cutoff,
    )
if __name__ == "__main__":
    PAIR_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/pairwise_method_comparisons_rank1_only.parquet")
    RMSD_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/pairwise_method_comparisons_rank1_with_binder_ca_rmsd.parquet")
    SHELL_RMSD_PATH = Path("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/pairwise_method_comparisons_rank1_with_binder_ca_rmsd_and_target_shell_rmsd.parquet")

    df = pd.read_parquet("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/prediction_records_new.parquet")

    pair_df = build_rank1_method_pairs(
        df,
        binder_col="binder_sequence",
        method_col="method",
        structure_file_col="path",
        rank_col="rank",
        file_type_col="file_type",
        binder_id_col="binder_chain_id",
        target_id_col="target_chain_id",
        keep_cols=["score", "score_name"],
    )

    # Save the base pair dataframe
    pair_df.to_parquet(PAIR_PATH, index=False)

    print(pair_df.head())
    print(f"Number of pairwise comparisons: {len(pair_df)}")
    print(f"Saved to: {PAIR_PATH}")

    # Compute binder CA RMSD

    results = Parallel(n_jobs=-2, verbose=10)(
        delayed(compute_binder_ca_rmsd_for_row)(row)
        for _, row in pair_df.iterrows()
    )

    results_df = pd.DataFrame(results)

    pair_df_with_rmsd = pd.concat([pair_df, results_df], axis=1)

    print(pair_df_with_rmsd[
        [
            "method_1",
            "method_2",
            "binder_ca_rmsd_align_binder",
            "n_ca_aligned",
            "status",
            "error",
        ]
    ].head())

    print(pair_df_with_rmsd["status"].value_counts(dropna=False))

    # Save dataframe with RMSD results
    pair_df_with_rmsd.to_parquet(RMSD_PATH, index=False)
    print(f"Saved RMSD results to: {RMSD_PATH}")

    shell_results = Parallel(n_jobs=-2, verbose=10)(
        delayed(compute_target_shell_rmsd_for_row)(row, 10.0)
        for _, row in pair_df_with_rmsd.iterrows()
    )

    shell_results_df = pd.DataFrame(shell_results)

    pair_df_with_shell_rmsd = pd.concat(
        [pair_df_with_rmsd.reset_index(drop=True), shell_results_df],
        axis=1
    )

    pair_df_with_shell_rmsd.to_parquet(SHELL_RMSD_PATH, index=False)
    print(f"Saved target-shell RMSD results to: {SHELL_RMSD_PATH}")