"""
This class serves as the core unification component for structural
predictions generated by multiple complex prediction methods. It loads structure
files from different modeling pipelines, extracts standardized metadata from each
individual model, and organizes the predictions into a unified dataset that can be
used for downstream comparative analyses.

The design separates two conceptual layers:

1. Single-Structure Extraction
   These operations process one structure file at a time and extract standardized
   metadata describing that prediction.
   - Method parsing: Determine which prediction method produced the structure
     based on directory structure or file paths.
   - Structure loading: Parse .pdb or .cif files using the appropriate Biopython
     parser.
   - Chain identification: Identify the target chain based on its known fixed
     sequence length and determine the corresponding binder chain(s).
   - Sequence extraction: Extract the binder amino acid sequence from the
     structure to provide a consistent identifier across prediction methods.
   - Optional structure features: Extract additional per-structure information
     (e.g., residue contacts or structural metadata) for later analysis.

2. Dataset-Level Unification
   After metadata has been extracted from all individual structures, the dataset
   is aggregated to enable cross-method comparison and filtering.
   - Binder grouping: Group predictions originating from different methods by
     their binder sequence, allowing consistent identification of equivalent
     complexes.
   - Master dataset compilation: Construct a unified dataset (e.g., dataframe or
     record list) containing standardized metadata for all predictions.
   - Smart filtering (future extension): Select representative predictions per
     binder (e.g., highest-ranking seed) while preserving access to all raw
     predictions.
   - Comparative analysis (future extension): Enable reliable cross-method
     structural comparisons such as binder-binder RMSD and target-target RMSD.

Overall flow:
    -> method parsing
    -> structure loading
    -> chain identification
    -> binder sequence extraction
    -> binder sequence matching
    -> unified dataset compilation
"""

from pathlib import Path
from joblib import Parallel, delayed
from dataclasses import dataclass, field
from Bio.PDB import PDBParser, MMCIFParser
from typing import Any
from Bio.Data.IUPACData import protein_letters_3to1
from dataclasses import asdict
import pandas as pd

@dataclass
class StructureRecord:
    path: Path
    file_type: str      # ".pdb" or ".cif"
    method: str         # prediction method name

    complex_name: str | None = None     # raw complex name from file/folder
    seed: int | None = None         # prediction seed / sample index
    rank: int | None = None         # model rank if provided

    target_chain_id: str | None = None
    binder_chain_id: str | None = None
    target_length: int | None = None
    binder_length: int | None = None

    binder_sequence: str | None = None
    target_sequence: str | None = None

    score: float | None = None
    score_name: str | None = None             # e.g. "ranking_score", "iptm"
    json_path: Path | None = None
    pkl_path: Path | None = None

    parse_success: bool = True
    error_message: str | None = None

class PredictionDataset:
    def __init__(self, root_dir, target_length=621):
        self.root_dir = Path(root_dir)
        self.target_length = target_length
        self.records = []

    def find_structure_files(self):
        pdb_files = list(self.root_dir.rglob("*.pdb"))
        cif_files = list(self.root_dir.rglob("*.cif"))
        return sorted(pdb_files + cif_files)
    
    def load_structure(self, path):
        path = Path(path)

        if path.suffix.lower() == ".pdb":
            parser = PDBParser(QUIET=True)
            return parser.get_structure(path.stem, str(path))
        elif path.suffix.lower() == ".cif":
            parser = MMCIFParser(QUIET=True)
            return parser.get_structure(path.stem, str(path))
        else:
            raise ValueError(f"Unsupported structure file type: {path}")
        
    def get_chain_lengths(self, structure):
        chain_lengths = {}
        
        for chain in structure.get_chains():
            residues = [res for res in chain.get_residues() if res.id[0] == " "]
            chain_lengths[chain.id] = len(residues)

        return chain_lengths
    
    def identify_target_and_binder(self, structure):
        target_chain = None
        binder_chain = None

        for chain in structure.get_chains():
            residues = [res for res in chain.get_residues() if res.id[0] == " "]
            chain_length = len(residues)

            if chain_length == self.target_length:
                target_chain = chain
            else:
                binder_chain = chain

        return target_chain, binder_chain
    
    def extract_chain_sequence(self, chain):
        sequence = []

        for residue in chain.get_residues():
            if residue.id[0] != " ":
                continue
            
            resname = residue.resname.title()
            one_letter = protein_letters_3to1.get(resname, "X")
            sequence.append(one_letter)
        
        return "".join(sequence)
    
    def detect_method(self, path):
        path = Path(path)

        relative_parts = path.relative_to(self.root_dir).parts
        method_folder = relative_parts[0]

        known_methods = {
            "AF2": "AF2",
            "AF3": "AF3",
            "Boltz-2": "Boltz-2",
            "Chai-1": "Chai-1",
            "HelixFold3": "HelixFold3",
            "OF2": "OF2",
            "OF3": "OF3",
            "Protenix": "Protenix",
            "SeedFold": "SeedFold",
        }

        return known_methods.get(method_folder, "unknown")
    
    def extract_record(self, path):
        path = Path(path)

        try:
            method = self.detect_method(path)
            file_type = path.suffix.lower()

            structure = self.load_structure(path)
            target_chain, binder_chain = self.identify_target_and_binder(structure)

            target_sequence = None
            binder_sequence = None
            target_chain_id = None
            binder_chain_id = None
            target_length = None
            binder_length = None

            if target_chain is not None:
                target_chain_id = target_chain.id
                target_sequence = self.extract_chain_sequence(target_chain)
                target_length = len(target_sequence)

            if binder_chain is not None:
                binder_chain_id = binder_chain.id
                binder_sequence = self.extract_chain_sequence(binder_chain)
                binder_length = len(binder_chain)

            record = StructureRecord(
                path=path,
                file_type=file_type,
                method=method,
                target_chain_id=target_chain_id,
                binder_chain_id=binder_chain_id,
                target_length=target_length,
                binder_length=binder_length,
                target_sequence=target_sequence,
                binder_sequence=binder_sequence,
                parse_success=True,
                error_message=None,
            )

            return record
        
        except Exception as e:
            return StructureRecord(
                path=path,
                file_type=path.suffix.lower(),
                method="unknown",
                parse_success=False,
                error_message=str(e),
            )
        
    def load_all_records(self, n_jobs=2, verbose=10):
        files = self.find_structure_files()

        records = Parallel(n_jobs=n_jobs, verbose=verbose)(
            delayed(self.extract_record)(path) for path in files
        )

        self.records = records
        return self.records
    
    def to_dataframe(self):
        df = pd.DataFrame([asdict(record) for record in self.records])

        for col in df.columns:
            df[col] = df[col].apply(lambda x: str(x) if isinstance(x, Path) else x)
        
        return df
    
    def save_parquet(self, output_path):
        df = self.to_dataframe()
        output_path = Path(output_path)
        df.to_parquet(output_path, index=False)

if __name__ == "__main__":

    dataset = PredictionDataset("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Predictions")

    records = dataset.load_all_records()

    print(f"Built {len(records)} records")
    print(records[:3])

    df = dataset.to_dataframe()
    print(df.head())

    dataset.save_parquet("/home/postyr/Assessing-AI-Scoring-Accuracy-for-De-Novo-Proteins/Analysis/Data/prediction_records.parquet")

    print("Parquet file saved.")